# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://projectfactory.github.io' # the base hostname & protocol for your site

title: 'Project FACTORY'
author: 'Cédric Févotte'

languages: [ 'en', 'de' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

default_header_img_dimensions: 'width="1024" height="1024"'
default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Wesite for the ERC project FACTORY'
  - scope:
      path: 'de'
    values:
      lang: de
      description: 'Wesite for the ERC project FACTORY'
  - scope:
      path: 'en'
    values:
      lang: en

# CSS Minification
sass:
  style: compressed
